apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-credentials
  labels:
    app: jenkins
data:
  jenkins-credentials.txt: |
    webhook-url=https://github.com/example/webhook
    webhook-secret=your-webhook-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          env:
            - name: ADMIN_USER
              value: admin
            - name: ADMIN_PASSWORD
              value: jenkins!
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            - name: jenkins-credentials
              mountPath: /run/secrets/jenkins-credentials
              readOnly: true
      volumes:
        - name: jenkins-data
          emptyDir: {}
        - name: jenkins-credentials
          configMap:
            name: jenkins-credentials

        # - name: jenkins-credentials
        #   secret:
        #     secretName: jenkins-credentials
