apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
        - name: init-jenkins
          image: jenkins/jenkins:lts
          env:
            - name: ADMIN_USER
              value: admin
            - name: ADMIN_PASSWORD
              value: jenkins!
          command:
            - sh
            - -c
            - |
              echo "jenkins.model.Jenkins.instance.securityRealm.createAccount('$ADMIN_USER', '$ADMIN_PASSWORD')" | java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080/ groovy =
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          env:
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          emptyDir: {}

        # - name: jenkins-credentials
        #   secret:
        #     secretName: jenkins-credentials
