apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          command:
            - /bin/sh
            - -c
            - |
              until curl -s -o /dev/null http://localhost:8080/login; do
                echo "Waiting for Jenkins to be ready..."
                sleep 5
              done
              echo "Jenkins is ready. Initializing..."
              # Add your initialization script here to create the admin user
              ADMIN_USER=admin_username
              ADMIN_PASSWORD=admin_password
              curl -X POST -d "username=${ADMIN_USER}&password1=${ADMIN_PASSWORD}&password2=${ADMIN_PASSWORD}" http://localhost:8080/securityRealm/createAccountByAdmin
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          emptyDir: {}

        # - name: jenkins-credentials
        #   secret:
        #     secretName: jenkins-credentials
