apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: node-js-postgresql-crud-example
spec:
  image: 3141hjkl/node-js-postgresql-crud-example
  interval: 1m0s
  accessFrom:
    namespaceSelectors:
      - matchLabels: {}
