---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-postgresql-crud-example
spec:
  selector:
    matchLabels:
      app: node-js-postgresql-crud-example
  template:
    metadata:
      labels:
        app: node-js-postgresql-crud-example
    spec:
      containers:
      - name: node-js-postgresql-crud-example
        image: 3141hjkl/node-js-postgresql-crud-example:1.0.5
        command: [ "pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]
---
apiVersion: v1
kind: Service
metadata:
  name: node-js-postgresql-crud-example
  labels:
    app: node-js-postgresql-crud-example
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: node-js-postgresql-crud-example
