apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-js-postgresql-crud-example
spec:
  imageRepositoryRef:
    name: node-js-postgresql-crud-example
    namespace: development
  filterTags:
    pattern: '^1.0.5-(?P<id>[0-9]+)$'
    extract: '$id.0.0'
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-js-postgresql-crud-example-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-js-postgresql-crud-example
  minReplicas: 2 # Minimum number of replicas
  maxReplicas: 5 # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-postgresql-crud-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js-postgresql-crud-example
  template:
    metadata:
      labels:
        app: node-js-postgresql-crud-example
    spec:
      containers:
      - name: node-js-postgresql-crud-example
        image: 3141hjkl/node-js-postgresql-crud-example:1.0.5-35 # {"$imagepolicy": "development:node-js-postgresql-crud-example"}
        resources:
          requests:
            cpu: 250m
        ports:
        - containerPort: 4000
        command: ["pm2-runtime", "start", "ecosystem.config.js", "--env", "development"]
---
apiVersion: v1
kind: Service
metadata:
  name: node-js-postgresql-crud-example
  labels:
    app: node-js-postgresql-crud-example
spec:
  type: ClusterIP
  ports:
    - port: 4000
  selector:
    app: node-js-postgresql-crud-example
