apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.7.0  # Example version, replace with the desired version
  interval: 1h0m0s
  values:
    postgresqlUsername: postgres
    postgresqlPassword: 123
    postgresqlDatabase: testdb
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: ClusterIP